// @ts-nocheck
import type { SiteStructure, Selectors } from '../types';

export function generateMadaraBaseClass(
  _structure: SiteStructure,
  _selectors: Selectors,
): string {
  // @ts-nocheck
  return `/**
  * ${_structure.siteName} - Madara Base Plugin
  * Auto-generated by LNReader Extractor
  * Site: ${_structure.baseUrl}
  * Type: Madara CMS (WordPress + Madara Theme)
  */

const Cheerio = require('cheerio');
const { fetchApi } = require('@libs/fetch');
const dayjs = require('dayjs');
const { NovelStatus } = require('@libs/novelStatus');
const { defaultCover } = require('@libs/defaultCover');

class MadaraBasePlugin {
  constructor(config) {
    this.id = config.id;
    this.name = config.name || config.sourceName;
    this.icon = config.icon || 'multisrc/madara/icon.png';
    this.site = config.sourceSite;
    this.version = config.version || '2.2.0';
    this.options = config.options || { lang: 'Spanish', down: true };
    this.filters = config.filters || {};
    this.hideLocked = config.hideLocked || false;
    this.customSelectors = config.customSelectors || {};
  }

  // Selector getters with fallback chain
  getSelector(key) {
    return this.customSelectors[key] || MADARA_SELECTORS[key] || [];
  }

  getFirstSelector(key) {
    const selectors = this.getSelector(key);
    return selectors.length > 0 ? selectors[0] : '';
  }

  // Main fetch with Cloudflare handling
  async getCheerio(url, skipChallengeCheck = false) {
    try {
      const res = await fetchApi(url, {
        headers: { 'Cache-Control': 'no-cache' },
      });
      
      if (!res.ok && !skipChallengeCheck) {
        throw new Error(\`Could not reach site (\${res.status}) try to open in webview.\`);
      }
      
      const html = await res.text();
      const $ = Cheerio.load(html);
      
      const title = $('title').text().trim();
      if (this.getHostname(url) !== this.getHostname(res.url) ||
          title === 'Bot Verification' ||
          title === 'You are being redirected...' ||
          title === 'Un instant...' ||
          title === 'Just a moment...' ||
          title === 'Redirecting...') {
        throw new Error('Captcha error, please open in webview');
      }
      
      return $;
    } catch (error) {
      throw error;
    }
  }

  getHostname(url) {
    const hostname = new URL(url).hostname;
    return hostname.replace('www.', '');
  }

  parseData(dateText) {
    const dayjs = require('dayjs');
    const now = dayjs();
    const match = dateText.match(/(\\d+)/);
    const num = match ? parseInt(match[1], 10) : 0;
    
    if (!num) return dateText;
    
    const lowerText = dateText.toLowerCase();
    if (lowerText.match(/detik|segundo|second|วินาที/)) return now.subtract(num, 'second').format('LL');
    if (lowerText.match(/menit|dakika|min|minute|minuto|นาที|دقائق/)) return now.subtract(num, 'minute').format('LL');
    if (lowerText.match(/jam|saat|heure|hora|hour|ชั่วโมง|giờ|ore|ساعة|小时/)) return now.subtract(num, 'hours').format('LL');
    if (lowerText.match(/hari|gün|jour|día|dia|day|วัน|ngày|giorni|أيام|天/)) return now.subtract(num, 'days').format('LL');
    if (lowerText.match(/week|semana/)) return now.subtract(num, 'week').format('LL');
    if (lowerText.match(/month|mes/)) return now.subtract(num, 'month').format('LL');
    if (lowerText.match(/year|año/)) return now.subtract(num, 'year').format('LL');
    
    return dayjs(dateText).isValid() ? dayjs(dateText).format('LL') : dateText;
  }

  // Translate Dragontea encoded content
  translateDragontea($) {
    if (this.id !== 'dragontea') return $;
    const html = $.html().replace(/\\n/g, '').replace(/<br\\s*\\/?>/g, '\\n');
    const $2 = Cheerio.load(html);
    $2.find('*').addBack().contents().filter((i, el) => el.nodeType === 3).each((i, el) => {
      const text = $2(el).text().normalize('NFD').split('').map(c => {
        const normalized = c.normalize('NFC');
        const idx = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'.indexOf(normalized);
        return idx >= 0 ? 'zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA'[idx] + c.slice(normalized.length) : c;
      }).join('');
      $2(el).replaceWith($2(el).text().replace('\\n', '<br>'));
    });
    return $2;
  }

  parseNovels($) {
    const novels = [];
    const titleSel = this.getFirstSelector('novelTitle');
    const coverSel = this.getFirstSelector('novelCover');
    const urlSel = this.getFirstSelector('searchUrl') || this.getFirstSelector('popularUrl');
    
    // @ts-ignore
    $${this.escapeSelector(
      this.getFirstSelector('popularList') ||
        '.page-item-detail, .c-tabs-item__content',
    )}.each((i, el) => {
      const $el = $(el);
      const title = $el.find(titleSel).text().trim();
      const url = $el.find(urlSel).attr('href') || '';
      if (title && url) {
        const cover = $el.find(coverSel).attr('data-src') || 
                     $el.find(coverSel).attr('data-lazy-src') || 
                     $el.find(coverSel).attr('src') || 
                     defaultCover;
        novels.push({ name: title, cover, path: url.replace(/https?:\\/\\/.*?\\//, '') });
      }
    });
    return novels;
  }

  // Popular novels with filters
  async popularNovels(page, options = {}) {
    const { showLatestNovels, filters } = options;
    let url = this.getFirstSelector('popularUrlTemplate') || \`\${this.site}/page/\${page}/?s=&post_type=wp-manga\`;
    
    if (showLatestNovels) url += '&m_orderby=latest';
    if (filters) {
      for (const [key, filter] of Object.entries(filters)) {
        if (Array.isArray(filter.value)) {
          filter.value.forEach(v => { url += \`&\${key}=\${v}\`; });
        } else if (filter.value) {
          url += \`&\${key}=\${filter.value}\`;
        }
      }
    }
    
    const $ = await this.getCheerio(url, page !== 1);
    return this.parseNovels($);
  }

  // Parse novel detail
  async parseNovel(novelPath) {
    const url = \`\${this.site}\${novelPath}\`;
    const $ = await this.getCheerio(url);
    
    // Remove badges
    $('.manga-title-badges, #manga-title span').remove();
    
    const novel = {
      path: novelPath,
      name: '',
      cover: defaultCover,
      genres: '',
      author: '',
      artist: '',
      status: NovelStatus.Unknown,
      summary: '',
      rating: 0,
      chapters: [],
    };
    
    // Title
    const titleSel = this.getFirstSelector('novelTitle');
    novel.name = $(titleSel).text().trim() || $('#manga-title h1').text().trim() || $('.manga-title').text().trim() || '';
    
    // Cover
    const coverSel = this.getFirstSelector('novelCover');
    novel.cover = $(coverSel).attr('data-lazy-src') || 
                  $(coverSel).attr('data-src') || 
                  $(coverSel).attr('src') || 
                  defaultCover;
    
    // Meta
    $('.post-content_item, .post-content').each((i, el) => {
      const $el = $(el);
      const header = $el.find('h5').text().trim();
      const content = $el.find('.summary-content, .summary_content');
      
      switch (header) {
        case 'Genre(s)':
        case 'Genre':
        case 'Tags(s)':
        case 'Tag(s)':
        case 'Tags':
        case 'Género(s)':
        case 'Kategori':
        case 'التصنيفات':
          novel.genres = novel.genres 
            ? novel.genres + ', ' + content.find('a').map((i, a) => $(a).text()).get().join(', ')
            : content.find('a').map((i, a) => $(a).text()).get().join(', ');
          break;
        case 'Author(s)':
        case 'Author':
        case 'Autor(es)':
        case 'المؤلف':
        case 'المؤلف (ين)':
          novel.author = content.text().trim();
          break;
        case 'Status':
        case 'Novel':
        case 'Estado':
        case 'Durum':
          novel.status = content.text().trim().includes('OnGoing') || content.text().trim().includes('مستمرة') 
            ? NovelStatus.Ongoing 
            : NovelStatus.Completed;
          break;
        case 'Artist(s)':
          novel.artist = content.text().trim();
          break;
      }
    });
    
    // Fallback genres
    if (!novel.genres) novel.genres = $('.genres-content').text().trim();
    if (!novel.status) novel.status = $('.manga-status').text().trim().includes('OnGoing') ? NovelStatus.Ongoing : NovelStatus.Completed;
    if (!novel.author) novel.author = $('.manga-author a').text().trim();
    if (!novel.author) novel.author = $('.manga-authors').text().trim();
    novel.rating = parseFloat($('.post-rating span').text().trim()) || 0;
    
    // Summary
    $('div.summary__content .code-block, script, noscript').remove();
    novel.summary = this.translateDragontea($('div.summary__content')).text().trim() || 
      $('#tab-manga-about').text().trim() || 
      $('.post-content_item h5:contains("Summary")').next().find('span').map((i, a) => $(a).text()).get().join('\\n\\n').trim() || 
      $('.manga-summary p').map((i, a) => $(a).text()).get().join('\\n\\n').trim() || 
      $('.manga-excerpt p').map((i, a) => $(a).text()).get().join('\\n\\n').trim();
    
    // Chapters
    const chapters = [];
    let totalChapters = 0;
    let html = '';
    
    if (this.options?.useNewChapterEndpoint) {
      const res = await fetchApi(this.site + novelPath + 'ajax/chapters/', {
        method: 'POST',
        referrer: this.site + novelPath,
      });
      html = await res.text();
    } else {
      const mangaId = $('.rating-post-id').attr('value') || $('#manga-chapters-holder').attr('data-id') || '';
      if (mangaId) {
        const formData = new FormData();
        formData.append('action', 'manga_get_chapters');
        formData.append('manga', mangaId);
        const res = await fetchApi(this.site + 'wp-admin/admin-ajax.php', { method: 'POST', body: formData });
        html = await res.text();
      }
    }
    
    if (html && html !== '0') {
      const $ch = Cheerio.load(html);
      totalChapters = $ch('.wp-manga-chapter').length;
      
      $ch('.wp-manga-chapter').each((i, el) => {
        const $el = $ch(el);
        let name = $el.find('a').text().trim();
        const isLocked = $el.attr('class').includes('premium-block');
        if (isLocked) name = '🔒 ' + name;
        
        const dateText = $el.find('span.chapter-release-date').text().trim();
        const releaseTime = dateText ? this.parseData(dateText) : dayjs().format('LL');
        
        const href = $el.find('a').attr('href') || '';
        if (!href || href === '#' || (isLocked && this.hideLocked)) return;
        
        chapters.push({
          name,
          path: href.replace(/https?:\\/\\/.*?\\//, ''),
          releaseTime,
          chapterNumber: totalChapters - i,
        });
      });
    }
    
    novel.chapters = chapters.reverse();
    return novel;
  }

  // Parse chapter content
  async parseChapter(chapterPath) {
    const url = \`\${this.site}\${chapterPath}\`;
    const $ = await this.getCheerio(url);
    
    const contentSel = this.getFirstSelector('chapterContent');
    const $content = $(contentSel) || $('.text-left') || $('.text-right') || $('.entry-content') || $('.c-blog-post > div > div:nth-child(2)');
    
    return this.translateDragontea($content).html() || '';
  }

  // Search novels
  async searchNovels(query, page) {
    const url = \`\${this.site}/page/\${page}/?s=\${encodeURIComponent(query)}&post_type=wp-manga\`;
    const $ = await this.getCheerio(url, true);
    return this.parseNovels($);
  }
}

const MADARA_SELECTORS = {
  // Novel list
  popularList: ['.page-item-detail', '.c-tabs-item__content'],
  novelTitle: ['.post-title a', '.manga-title a', 'h3 a', 'h4 a'],
  novelCover: ['img@data-src', 'img@data-lazy-src', 'img@src'],
  popularUrl: ['@href'],
  popularCover: ['img@data-src', 'img@data-lazy-src', 'img@src'],
  
  // Novel detail
  novelTitle: ['.post-title h1', '#manga-title h1', '.manga-title'],
  novelCover: ['.summary_image > a > img@data-lazy-src', '.summary_image > a > img@data-src', '.summary_image > a > img@src'],
  novelSummary: ['div.summary__content', '#tab-manga-about', '.post-content_item h5:contains("Summary") + .summary-content span', '.manga-summary p', '.manga-excerpt p'],
  novelAuthor: ['.post-content_item h5:contains("Author") + .summary-content', '.manga-author a', '.manga-authors'],
  novelArtist: ['.post-content_item h5:contains("Artist") + .summary-content'],
  novelStatus: ['.post-content_item h5:contains("Status") + .summary-content', '.manga-status'],
  novelGenres: ['.post-content_item h5:contains("Genre") + .summary-content', '.genres-content'],
  novelRating: ['.post-rating span'],
  
  // Chapters
  chapterContainer: ['.wp-manga-chapter', '#manga-chapters-holder'],
  chapterSelector: ['.wp-manga-chapter a'],
  chapterTitle: ['a'],
  chapterUrl: ['@href'],
  chapterDate: ['span.chapter-release-date'],
  
  // Chapter content
  chapterContent: ['.text-left', '.text-right', '.entry-content', '.c-blog-post > div > div:nth-child(2)'],
  
  // Search
  searchResults: ['.page-item-detail', '.c-tabs-item__content'],
  searchTitle: ['.post-title a', '.manga-title a', 'h3 a'],
  searchUrl: ['@href'],
  searchCover: ['img@data-src', 'img@data-lazy-src', 'img@src'],
  
  // Pagination
  pagination: ['.pagination', '.wp-pagenavi'],
  nextPage: ['a.next', 'a[rel="next"]', '.next-page'],
  loadMoreButton: ['.load-more', 'button:contains("Load more")', 'button:contains("Cargar más")'],
  
  // Volume tabs
  volumeTabs: ['.volume-tabs', '.volumes-tabs', '.chapter-volumes', '.nav-tabs', '.c-tabs'],
  volumeTab: ['.tab', '.tab-pane', '[role="tabpanel"]', '.c-tabs-item__content'],
  volumeChapterContainer: ['.wp-manga-chapter', '.chapter-list'],
};

module.exports = MadaraBasePlugin;
`;
}
