import type { SiteStructure, Selectors, ExtractorOptions } from '../types';
import { generateMadaraBaseClass } from './baseClassGenerator';

export function generatePlugin(
  structure: SiteStructure,
  selectors: Selectors,
  options: ExtractorOptions,
): { pluginCode: string; baseClassCode?: string } {
  const { siteType, siteName: _siteName, baseUrl: _baseUrl } = structure;

  let pluginCode: string;
  let baseClassCode: string | undefined;

  switch (siteType) {
    case 'madara-cms':
      baseClassCode = generateMadaraBaseClass(structure, selectors);
      pluginCode = generateMadaraPlugin(structure, selectors, options);
      break;
    case 'lightnovelwp-cms':
      pluginCode = generateLightnovelwpPlugin(structure, selectors, options);
      break;
    case 'api-json':
      pluginCode = generateApiPlugin(structure, selectors, options);
      break;
    case 'novelyra-custom':
      pluginCode = generateNovelyraPlugin(structure, selectors, options);
      break;
    default:
      pluginCode = generateGenericPlugin(structure, selectors, options);
  }

  return { pluginCode, baseClassCode };
}

function generateMadaraPlugin(
  structure: SiteStructure,
  selectors: Selectors,
  options: ExtractorOptions,
): string {
  const siteId =
    options.siteId ||
    structure.baseUrl
      .replace(/https?:\/\//, '')
      .replace(/\./g, '-')
      .replace(/[^a-z0-9-]/g, '');

  const hasNewChapterEndpoint =
    structure.chapterPattern.type === 'ajax-pages' &&
    structure.chapterPattern.ajaxPages?.endpoint?.includes('ajax/chapters');

  // @ts-nocheck
  return `/**
  * ${structure.siteName} Plugin
  * Auto-generated by LNReader Extractor
  * Source: ${structure.baseUrl}
  * Type: Madara CMS (WordPress + Madara Theme)
  * Generated: ${new Date().toISOString()}
  */

const MadaraBasePlugin = require('./plugin.base');

const ${capitalizeFirst(siteId)}Plugin = new MadaraBasePlugin({
  id: '${siteId}',
  sourceSite: '${structure.baseUrl}',
  sourceName: '${escapeString(structure.siteName)}',
  version: '2.2.0',
  options: { 
    lang: '${options.lang || 'Spanish'}', 
    down: true,

(Showing lines 50-60 of 656. Use offset=51 to continue.)
    downSince: ${Date.now()},
    hasLocked: ${
      selectors.chapterSelector.some(
        s => s.includes('premium-block') || s.includes('locked'),
      )
        ? 'true'
        : 'false'
    },
    useNewChapterEndpoint: ${hasNewChapterEndpoint ? 'true' : 'false'},
  },
  customSelectors: {
    // Novel list
    popularList: [${formatSelectorArray(selectors.popularList)}],
    novelTitle: [${formatSelectorArray(selectors.novelTitle)}],
    novelCover: [${formatSelectorArray(selectors.novelCover)}],
    popularUrl: [${formatSelectorArray(selectors.popularUrl)}],
    popularCover: [${formatSelectorArray(selectors.popularCover)}],
    
    // Novel detail
    novelTitle: [${formatSelectorArray(selectors.novelTitle)}],
    novelCover: [${formatSelectorArray(selectors.novelCover)}],
    novelSummary: [${formatSelectorArray(selectors.novelSummary)}],
    novelAuthor: [${formatSelectorArray(selectors.novelAuthor)}],
    novelArtist: [${formatSelectorArray(selectors.novelArtist)}],
    novelStatus: [${formatSelectorArray(selectors.novelStatus)}],
    novelGenres: [${formatSelectorArray(selectors.novelGenres)}],
    novelRating: [${formatSelectorArray(selectors.novelRating)}],
    
    // Chapters
    chapterContainer: [${formatSelectorArray(selectors.chapterContainer)}],
    chapterSelector: [${formatSelectorArray(selectors.chapterSelector)}],
    chapterTitle: [${formatSelectorArray(selectors.chapterTitle)}],
    chapterUrl: [${formatSelectorArray(selectors.chapterUrl)}],
    chapterDate: [${formatSelectorArray(selectors.chapterDate)}],
    
    // Chapter content
    chapterContent: [${formatSelectorArray(selectors.chapterContent)}],
    
    // Search
    searchResults: [${formatSelectorArray(selectors.searchResults)}],
    searchTitle: [${formatSelectorArray(selectors.searchTitle)}],
    searchUrl: [${formatSelectorArray(selectors.searchUrl)}],
    searchCover: [${formatSelectorArray(selectors.searchCover)}],
    
    // Pagination
    pagination: [${formatSelectorArray(selectors.pagination)}],
    nextPage: [${formatSelectorArray(selectors.nextPage)}],
    loadMoreButton: [${formatSelectorArray(selectors.loadMoreButton)}],
    
    // Volume tabs
    volumeTabs: [${formatSelectorArray(selectors.volumeTabs)}],
    volumeTab: [${formatSelectorArray(selectors.volumeTab)}],
    volumeChapterContainer: [${formatSelectorArray(
      selectors.volumeChapterContainer,
    )}],
  },
});

module.exports = ${capitalizeFirst(siteId)}Plugin;
`;
}

function generateLightnovelwpPlugin(
  structure: SiteStructure,
  _selectors: Selectors,
  options: ExtractorOptions,
): string {
  const siteId =
    options.siteId ||
    structure.baseUrl
      .replace(/https?:\/\//, '')
      .replace(/\./g, '-')
      .replace(/[^a-z0-9-]/g, '');

  // @ts-nocheck
  return `/**
  * ${structure.siteName} Plugin
  * Auto-generated by LNReader Extractor
  * Source: ${structure.baseUrl}
  * Type: LightnovelWP Theme
  * Generated: ${new Date().toISOString()}
  */

const Cheerio = require('cheerio');
const { fetchApi } = require('@libs/fetch');
const { NovelStatus } = require('@libs/novelStatus');
const { defaultCover } = require('@libs/defaultCover');

class ${capitalizeFirst(siteId)}Plugin {
  constructor() {
    this.id = '${siteId}';
    this.name = '${escapeString(structure.siteName)}';
    this.site = '${structure.baseUrl}';
    this.version = '1.0.0';
    this.icon = '${structure.baseUrl}/favicon.ico';
    this.lang = '${options.lang || 'Spanish'}';
    this.filters = {};
  }

  async getCheerio(url) {
    const res = await fetchApi(url, { headers: { 'Cache-Control': 'no-cache' } });
    if (!res.ok) throw new Error(\`HTTP \${res.status}: \${url}\`);
    return Cheerio.load(await res.text());
  }

  async popularNovels(page, options = {}) {
    const url = \`\${this.site}/page/\${page}\`;
    const $ = await this.getCheerio(url);
    return this.parseNovels($);
  }

  parseNovels($) {
    const novels = [];
    $('.novel-item, .lnwp-chapter, .novel-list .item').each((i, el) => {
      const $el = $(el);
      const title = $el.find('.novel-title, h3 a, .title a').first().text().trim();
      const url = $el.find('a').first().attr('href') || '';
      const cover = $el.find('img').attr('data-src') || $el.find('img').attr('src') || defaultCover;
      if (title && url) {
        novels.push({ name: title, cover, path: url.replace(this.site, '') });
      }
    });
    return novels;
  }

  async parseNovel(novelPath) {
    const url = \`\${this.site}\${novelPath}\`;
    const $ = await this.getCheerio(url);
    
    const novel = {
      path: novelPath,
      name: $('.novel-title, h1.title, .book-title').text().trim() || 'Unknown',
      cover: $('img.cover, .novel-cover img, .book-cover img').attr('src') || defaultCover,
      summary: $('.summary, .description, .synopsis').text().trim(),
      author: $('.author, .novel-author, [class*="author"]').text().trim(),
      artist: '',
      status: NovelStatus.Unknown,
      genres: $('.genres, .tags, [class*="genre"]').text().trim(),
      chapters: [],
    };
    
    // Parse chapters
    const chapters = [];
    $('.lnwp-chapter-list a, .chapter-list a, .chapters a').each((i, el) => {
      const $el = $(el);
      const name = $el.text().trim();
      const href = $el.attr('href') || '';
      if (name && href) {
        chapters.push({
          name,
          path: href.replace(this.site, ''),
          chapterNumber: chapters.length + 1,
        });
      }
    });
    
    novel.chapters = chapters;
    return novel;
  }

  async parseChapter(chapterPath) {
    const url = \`\${this.site}\${chapterPath}\`;
    const $ = await this.getCheerio(url);
    
    $('script, style, .ads, .ad, nav, header, footer').remove();
    const content = $('.reading-content, .chapter-content, .text-content, article, .fr-view').html() || '';
    return content;
  }

  async searchNovels(query, page) {
    const url = \`\${this.site}/search?keyword=\${encodeURIComponent(query)}&page=\${page}\`;
    const $ = await this.getCheerio(url);
    return this.parseNovels($);
  }
}

module.exports = new ${capitalizeFirst(siteId)}Plugin();
`;
}

function generateApiPlugin(
  structure: SiteStructure,
  _selectors: Selectors,
  options: ExtractorOptions,
): string {
  const siteId =
    options.siteId ||
    structure.baseUrl
      .replace(/https?:\/\//, '')
      .replace(/\./g, '-')
      .replace(/[^a-z0-9-]/g, '');

  // @ts-nocheck
  return `/**
  * ${structure.siteName} Plugin
  * Auto-generated by LNReader Extractor
  * Source: ${structure.baseUrl}
  * Type: API JSON
  * Generated: ${new Date().toISOString()}
  */

const { fetchApi } = require('@libs/fetch');

class ${capitalizeFirst(siteId)}Plugin {
  constructor() {
    this.id = '${siteId}';
    this.name = '${escapeString(structure.siteName)}';
    this.site = '${structure.baseUrl}';
    this.apiSite = '${structure.baseUrl}api/';
    this.version = '1.0.0';
    this.lang = '${options.lang || 'Spanish'}';
    this.filters = {};
  }

  async fetchJson(url) {
    const res = await fetchApi(url, { headers: { 'Cache-Control': 'no-cache' } });
    return res.json();
  }

  mapNovelList(data) {
    const novels = [];
    (data.novels || data.data || []).forEach(item => {
      novels.push({
        name: item.nvl_title || item.title || item.name,
        cover: item.image ? \`\${this.apiSite}get-image/\${item.image}/novels/false\` : item.cover,
        path: \`novelas/\${item.id}/\${item.nvl_name || item.slug || item.name}/\`,
      });
    });
    return novels;
  }

  async popularNovels(page, options = {}) {
    const { filters } = options;
    let url = \`\${this.apiSite}novels?page=\${page}&order=rating\`;
    if (filters?.genres?.value?.length) {
      url += \`&genres=\${filters.genres.value.join(',')}\`;
    }
    const data = await this.fetchJson(url);
    return this.mapNovelList(data);
  }

  async searchNovels(query, page) {
    const url = \`\${this.apiSite}novels?page=\${page}&q=\${encodeURIComponent(query.toLowerCase())}\`;
    const data = await this.fetchJson(url);
    return this.mapNovelList(data);
  }

  async parseNovel(novelPath) {
    const novelId = novelPath.split('/')[1];
    const url = \`\${this.apiSite}novel/\${novelId}/reading\`;
    const data = await this.fetchJson(url);
    const novel = data.novel?.[0];
    
    if (!novel) throw new Error('Novel not found');
    
    return {
      path: novelPath,
      name: novel.nvl_title || 'Unknown',
      cover: \`\${this.apiSite}get-image/\${novel.image}/novels/false\`,
      summary: novel.nvl_content,
      author: novel.nvl_writer,
      genres: novel.genres?.map(g => g.genre_name).join(', '),
      status: novel.nvl_status,
      chapters: this.mapChapters(novelPath, novel.volumes),
    };
  }

  mapChapters(novelPath, volumes) {
    const chapters = [];
    (volumes || []).forEach(vol => {
      (vol.chapters || []).forEach(ch => {
        chapters.push({
          name: ch.chp_index_title,
          releaseTime: new Date(ch.createdAt).toDateString(),
          path: \${novelPath}\${ch.id}/\${ch.chp_name}/,
        });
      });
    });
    return chapters;
  }

  async parseChapter(chapterPath) {
    const chapterId = chapterPath.split('/')[3];
    const url = \`\${this.apiSite}novel-chapter/\${chapterId}\`;
    const data = await this.fetchJson(url);
    const chapter = data.chapter?.[0];
    return chapter?.chp_content || '';
  }
}

module.exports = new ${capitalizeFirst(siteId)}Plugin();
`;
}

function generateNovelyraPlugin(
  structure: SiteStructure,
  _selectors: Selectors,
  options: ExtractorOptions,
): string {
  const siteId =
    options.siteId ||
    structure.baseUrl
      .replace(/https?:\/\//, '')
      .replace(/\./g, '-')
      .replace(/[^a-z0-9-]/g, '');

  // @ts-nocheck
  return `/**
  * ${structure.siteName} Plugin
  * Auto-generated by LNReader Extractor
  * Source: ${structure.baseUrl}
  * Type: Custom (Novelyra-style)
  * Generated: ${new Date().toISOString()}
  */

const Cheerio = require('cheerio');
const { fetchApi } = require('@libs/fetch');

class ${capitalizeFirst(siteId)}Plugin {
  constructor() {
    this.id = '${siteId}';
    this.name = '${escapeString(structure.siteName)}';
    this.site = '${structure.baseUrl}';
    this.version = '1.0.0';
    this.lang = '${options.lang || 'Spanish'}';
    this.filters = {};
  }

  async getCheerio(url) {
    const res = await fetchApi(url);
    if (!res.ok) throw new Error(\`HTTP \${res.status}: \${url}\`);
    return Cheerio.load(await res.text());
  }

  async popularNovels(page, options = {}) {
    const url = page === 1 ? this.site : \`\${this.site}?page=\${page}\`;
    const $ = await this.getCheerio(url);
    return this.parseNovels($);
  }

  parseNovels($) {
    const novels = [];
    $('main a.group.block.min-w-0').each((i, el) => {
      const $el = $(el);
      const title = $el.find('h3').first().text().trim();
      const url = $el.attr('href') || '';
      const cover = $el.find('img').attr('src') || $el.find('img').attr('data-src') || '';
      if (title && url) {
        novels.push({ name: title, cover, path: url.replace(this.site, '').replace(/^\\/+/,'') });
      }
    });
    return novels;
  }

  async parseNovel(novelPath) {
    const url = \`\${this.site}\${novelPath}\`;
    const $ = await this.getCheerio(url);
    
    const title = $('h1').first().text().trim() || 'Unknown';
    const cover = $('#synopsis img').attr('src') || $('main img').first().attr('src') || '';
    const summary = this.extractSynopsis($);
    
    // Extract meta from synopsis text
    const synopsisText = $('#synopsis').text().replace(/\\u00a0/g, ' ').replace(/\\s+/g, ' ').trim();
    const authorMatch = synopsisText.match(/Author:\\s*(.+?)(?:\\s+Genre:|\\s+Status:|\\s+Platform:|\\s+Theme:|$)/i);
    const genreMatch = synopsisText.match(/Genre:\\s*(.+?)(?:\\s+Status:|\\s+Platform:|\\s+Theme:|$)/i);
    const statusMatch = synopsisText.match(/Status:\\s*(.+?)(?:\\s+Platform:|\\s+Theme:|$)/i);
    
    // Chapters
    const chapters = [];
    const seen = new Set();
    $('a[href*="/chapter-"]').each((i, el) => {
      const $el = $(el);
      const href = $el.attr('href') || '';
      const match = href.match(/\\/chapter-(\\d+)(?:\\/)?(?:[?#].*)?$/i);
      if (match) {
        const num = Number(match[1]);
        if (Number.isFinite(num)) {
          let path = href;
          if (path.startsWith(this.site)) path = path.slice(this.site.length);
          path = path.replace(/^\\/+/,'');
          if (!seen.has(path)) {
            seen.add(path);
            let name = $el.text().trim().replace(/\\s+/g, ' ');
            const dashIdx = name.indexOf(' - ');
            if (dashIdx > 0) name = name.slice(0, dashIdx).trim();
            name = name || \`Chapter \${num}\`;
            chapters.push({ name, path, chapterNumber: num });
          }
        }
      }
    });
    
    chapters.sort((a, b) => a.chapterNumber - b.chapterNumber);
    
    return {
      path: novelPath,
      name: title,
      cover: cover.startsWith('/') ? this.site + cover.slice(1) : cover,
      summary,
      author: authorMatch?.[1]?.trim(),
      genres: genreMatch?.[1]?.trim().replace(/\\s+/g, ', '),
      status: statusMatch?.[1]?.trim(),
      chapters,
    };
  }

  extractSynopsis($) {
    const $syn = $('#synopsis').first();
    if (!$syn.length) return '';
    $syn.find('button, script, style').remove();
    $syn.find('br').replaceWith('\\n');
    $syn.find('p, div').each((i, el) => {
      const text = $(el).text();
      if (text.trim() && !text.endsWith('\\n')) $(el).append('\\n');
    });
    const lines = $syn.text().split(/\\r?\\n/).map(l => l.replace(/\\u00a0/g, ' ').replace(/\\s+/g, ' ').trim()).filter(Boolean);
    if (!lines.length) return '';
    const premiseIdx = lines.findIndex(l => /^Premise\\s*:/i.test(l));
    const filtered = (premiseIdx >= 0 ? lines.slice(premiseIdx) : lines)
      .filter(l => !/^Author\\s*:/i.test(l) && !/^Genre\\s*:/i.test(l) && !/^Status\\s*:/i.test(l) && !/^Platform\\s*:/i.test(l) && !/^Core Theme\\s*:/i.test(l));
    const whyIdx = filtered.findIndex(l => /^Why\\s+/i.test(l) || /^What\\s+Makes\\s+/i.test(l) || /^Why\\s+".+"\\s+is\\s+Different/i.test(l));
    return (whyIdx >= 0 ? filtered.slice(0, whyIdx) : filtered).join('\\n');
  }

  async parseChapter(chapterPath) {
    const url = \`\${this.site}\${chapterPath}\`;
    const $ = await this.getCheerio(url);
    
    $('script, style, iframe, ins, nav, header, footer, aside').remove();
    const $content = $('article').first();
    if (!$content.length) return 'Content not found';
    
    const paragraphs = [];
    $content.find('p').each((i, el) => {
      const text = $(el).text().trim().replace(/\\s+/g, ' ');
      if (text) paragraphs.push(text);
    });
    
    if (paragraphs.length === 0) {
      const text = $content.text().trim().replace(/\\s+/g, ' ');
      if (text) paragraphs.push(text);
    }
    
    return paragraphs.map(p => \`<p>\${p.replace(/</g,'<').replace(/>/g,'>')}</p>\`).join('');
  }

  async searchNovels(query, page) {
    const url = \`\${this.site}search?q=\${encodeURIComponent(query)}\${page > 1 ? '&page=' + page : ''}\`;
    const $ = await this.getCheerio(url);
    return this.parseNovels($);
  }
}

module.exports = new ${capitalizeFirst(siteId)}Plugin();
`;
}

function generateGenericPlugin(
  structure: SiteStructure,
  selectors: Selectors,
  options: ExtractorOptions,
): string {
  const siteId =
    options.siteId ||
    structure.baseUrl
      .replace(/https?:\/\//, '')
      .replace(/\./g, '-')
      .replace(/[^a-z0-9-]/g, '');
  const chapterPattern = structure.chapterPattern;

  let parsePageMethod = '';

  if (chapterPattern.type === 'pagination') {
    parsePageMethod = `
  async parsePage(novelPath, page) {
    const url = \`\${this.site}\${novelPath}?page=\${page}\`;
    const $ = await this.getCheerio(url);
    return { chapters: this.extractChapters($) };
  }`;
  } else if (chapterPattern.type === 'volume-tabs') {
    parsePageMethod = `
  async parsePage(novelPath, page) {
    // page = volume index (0-based)
    const $ = await this.getCheerio(\`\${this.site}\${novelPath}\`);
    const tabs = $('${_getSel(selectors, 'volumeTab')}');
    const tab = tabs.eq(page);
    if (!tab.length) return { chapters: [] };
    return { chapters: this.extractChaptersFromTab(tab) };
  }`;
  } else if (chapterPattern.type === 'ajax-pages') {
    parsePageMethod = `
  async parsePage(novelPath, page) {
    const novelId = this.extractNovelId(novelPath);
    const res = await fetchApi('\${this.site}/api/chapters', {
      method: 'POST',
      body: JSON.stringify({ novelId, page, perPage: 50 }),
      headers: { 'Content-Type': 'application/json' }
    });
    const data = await res.json();
    return { chapters: this.parseAjaxChapters(data) };
  }`;
  } else {
    parsePageMethod = `
  // parsePage not needed for single-page/embedded-json sites
  // All chapters are returned by parseNovel
  parsePage: undefined`;
  }

  // @ts-nocheck
  return `/**
  * ${structure.siteName} Plugin
  * Auto-generated by LNReader Extractor
  * Source: ${structure.baseUrl}
  * Type: ${structure.siteType}
  * Chapter Pattern: ${chapterPattern.type}
  * Generated: ${new Date().toISOString()}
  */

const Cheerio = require('cheerio');
const { fetchApi } = require('@libs/fetch');
const { NovelStatus } = require('@libs/novelStatus');
const { defaultCover } = require('@libs/defaultCover');

class ${capitalizeFirst(siteId)}Plugin {
  constructor() {
    this.id = '${siteId}';
    this.name = '${escapeString(structure.siteName)}';
    this.site = '${structure.baseUrl}';
    this.version = '1.0.0';
    this.lang = '${options.lang || 'Spanish'}';
    this.filters = {};
  }

  async getCheerio(url) {
    const res = await fetchApi(url, { headers: { 'Cache-Control': 'no-cache' } });
    if (!res.ok) throw new Error(\`HTTP \${res.status}: \${url}\`);
    return Cheerio.load(await res.text());
  }

  extractChapters($) {
    const chapters = [];
    $('${_getSel(selectors, 'chapterSelector')}').each((i, el) => {
      const $el = $(el);
      const title = $el.find('${_getSel(
        selectors,
        'chapterTitle',
      )}').first().text().trim() || $el.text().trim();
      const url = $el.attr('${_getSel(selectors, 'chapterUrl').replace(
        '@',
        '',
      )}') || $el.attr('href') || '';
      if (title && url) {
        chapters.push({ name: title, path: url.replace(this.site, ''), chapterNumber: chapters.length + 1 });
      }
    });
    return chapters;
  }

  extractChaptersFromTab($tab) {
    const chapters = [];
    $tab.find('${_getSel(selectors, 'volumeChapterContainer')} ${_getSel(
    selectors,
    'chapterSelector',
  )}').each((i, el) => {
      const $el = $(el);
      const title = $el.find('${_getSel(
        selectors,
        'chapterTitle',
      )}').first().text().trim() || $el.text().trim();
      const url = $el.attr('${_getSel(selectors, 'chapterUrl').replace(
        '@',
        '',
      )}') || $el.attr('href') || '';
      if (title && url) {
        chapters.push({ name: title, path: url.replace(this.site, ''), chapterNumber: chapters.length + 1 });
      }
    });
    return chapters;
  }

  async popularNovels(page, options = {}) {
    const url = \`\${this.site}/page/\${page}\`;
    const $ = await this.getCheerio(url);
    return this.parseNovels($);
  }

  parseNovels($) {
    const novels = [];
    $('${_getSel(selectors, 'popularList')}').each((i, el) => {
      const $el = $(el);
      const title = $el.find('${_getSel(
        selectors,
        'popularTitle',
      )}').first().text().trim();
      const url = $el.find('${_getSel(
        selectors,
        'popularUrl',
      )}').attr('href') || '';
      const cover = $el.find('${_getSel(
        selectors,
        'popularCover',
      )}').attr('src') || defaultCover;
      if (title && url) {
        novels.push({ name: title, cover, path: url.replace(this.site, '') });
      }
    });
    return novels;
  }

  async parseNovel(novelPath) {
    const url = \`\${this.site}\${novelPath}\`;
    const $ = await this.getCheerio(url);
    
    const novel = {
      path: novelPath,
      name: $('${_getSel(selectors, 'novelTitle')}').text().trim() || 'Unknown',
      cover: $('${_getSel(
        selectors,
        'novelCover',
      )}').attr('src') || defaultCover,
      summary: $('${_getSel(selectors, 'novelSummary')}').text().trim(),
      author: $('${_getSel(selectors, 'novelAuthor')}').text().trim(),
      artist: $('${_getSel(selectors, 'novelArtist')}').text().trim(),
      status: NovelStatus.Unknown,
      genres: $('${_getSel(selectors, 'novelGenres')}').text().trim(),
      chapters: this.extractChapters($),
    };
    
    return novel;
  }

  async parseChapter(chapterPath) {
    const url = \${this.site}\${chapterPath};
    const $ = await this.getCheerio(url);
    
    // Remove unwanted elements
    (selectors.removeFromContent || []).forEach(selector => $(selector).remove());
    
    const content = $('${_getSel(selectors, 'chapterContent')}').html() || '';
    return content;
  }

  async searchNovels(query, page) {
    const url = \`\${this.site}/search?q=\${encodeURIComponent(query)}&page=\${page}\`;
    const $ = await this.getCheerio(url);
    return this.parseNovels($);
  }

  ${parsePageMethod}
}

module.exports = new ${capitalizeFirst(siteId)}Plugin();
`;
}

function formatSelectorArray(arr: string[]): string {
  return (arr || []).map(s => `'${escapeString(s)}'`).join(', ');
}

function escapeString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}

function capitalizeFirst(str: string): string {
  return (
    str.charAt(0).toUpperCase() +
    str.slice(1).replace(/[-_](.)/g, (_, c) => c.toUpperCase())
  );
}

function _getSel(selectors: Selectors, key: keyof Selectors): string {
  const arr = selectors[key];
  return arr && arr.length > 0 ? arr[0] : '';
}
